export const GENRES_LOADED = 'GENRES_LOADED';
export const START_GENRES_LOADING = 'START_GENRES_LOADING';
export const STOP_GENRES_LOADING = 'STOP_GENRES_LOADING';
export const ERROR_LOADING_GENRES = 'ERROR_LOADING_GENRES';