export const MOVIES_LOADED = 'MOVIES_LOADED';
export const START_MOVIES_LOADING = 'START_MOVIES_LOADING';
export const STOP_MOVIES_LOADING = 'STOP_MOVIES_LOADING';
export const ERROR_LOADING_MOVIES = 'ERROR_LOADING_MOVIES';
export const CURRENT_PAGE = 'CURRENT_PAGE';